# Generated by Django 3.2.4 on 2021-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(default=0.0)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('spo2', models.IntegerField()),
            ],
        ),
    ]
